In [0]:
#amount of similarity between predictions and actuals
#least possible score is -1 which is given when the predictions are furthest away from actuals
#score of 0.6+ is considered to be a really good score
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

In [0]:
actuals = np.array([4, 4, 3, 4, 4, 4, 1, 1, 2, 1])
preds   = np.array([0, 2, 1, 0, 0, 0, 1, 1, 2, 1])

In [3]:
actuals.shape

(10,)

In [4]:
confusion_matrix(actuals, preds)

array([[0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [4, 0, 1, 0, 0]])

In [5]:
w = np.zeros((5,5)); w

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [0]:
for i in range(len(w)):
    for j in range(len(w)):
        w[i][j] = float(((i-j)**2)/16) #as per formula, for the competition, N=5

In [7]:
w

array([[0.    , 0.0625, 0.25  , 0.5625, 1.    ],
       [0.0625, 0.    , 0.0625, 0.25  , 0.5625],
       [0.25  , 0.0625, 0.    , 0.0625, 0.25  ],
       [0.5625, 0.25  , 0.0625, 0.    , 0.0625],
       [1.    , 0.5625, 0.25  , 0.0625, 0.    ]])

In [0]:
N=5
act_hist=np.zeros([N])
for item in actuals: 
    act_hist[item]+=1

In [0]:
pred_hist=np.zeros([N])
for item in preds: 
    pred_hist[item]+=1

In [10]:
print(f'Actuals value counts:{act_hist}, Prediction value counts:{pred_hist}')

Actuals value counts:[0. 3. 1. 1. 5.], Prediction value counts:[4. 4. 2. 0. 0.]


In [11]:
E = np.outer(act_hist, pred_hist); E

array([[ 0.,  0.,  0.,  0.,  0.],
       [12., 12.,  6.,  0.,  0.],
       [ 4.,  4.,  2.,  0.,  0.],
       [ 4.,  4.,  2.,  0.,  0.],
       [20., 20., 10.,  0.,  0.]])

In [12]:
E = E/E.sum(); E.sum()

1.0

In [14]:
O = confusion_matrix(actuals, preds)
O = O/O.sum(); O.sum()

1.0

In [15]:
E

array([[0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.12, 0.12, 0.06, 0.  , 0.  ],
       [0.04, 0.04, 0.02, 0.  , 0.  ],
       [0.04, 0.04, 0.02, 0.  , 0.  ],
       [0.2 , 0.2 , 0.1 , 0.  , 0.  ]])

In [16]:
O

array([[0. , 0. , 0. , 0. , 0. ],
       [0. , 0.3, 0. , 0. , 0. ],
       [0. , 0. , 0.1, 0. , 0. ],
       [0. , 0.1, 0. , 0. , 0. ],
       [0.4, 0. , 0.1, 0. , 0. ]])

In [17]:
num=0
den=0
for i in range(len(w)):
    for j in range(len(w)):
        num+=w[i][j]*O[i][j]
        den+=w[i][j]*E[i][j]
 
weighted_kappa = (1 - (num/den)); weighted_kappa

-0.139240506329114